// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmI1jXf0yve6zGY5Stc-BwI_HC9cmb6ZQ',
    appId: '1:965170259379:web:5a54746eec4d21c9d4d7c6',
    messagingSenderId: '965170259379',
    projectId: 'pblkb-bf750',
    authDomain: 'pblkb-bf750.firebaseapp.com',
    storageBucket: 'pblkb-bf750.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFYfGej-iSWn1EIbNKHPVgSSn2PxntbYQ',
    appId: '1:965170259379:android:72374d1411cc5d73d4d7c6',
    messagingSenderId: '965170259379',
    projectId: 'pblkb-bf750',
    storageBucket: 'pblkb-bf750.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIitnvIDeiv31KXtDsEkvEg2N3KvvxZ24',
    appId: '1:965170259379:ios:c9da254bd08327d4d4d7c6',
    messagingSenderId: '965170259379',
    projectId: 'pblkb-bf750',
    storageBucket: 'pblkb-bf750.firebasestorage.app',
    iosBundleId: 'com.example.pbl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIitnvIDeiv31KXtDsEkvEg2N3KvvxZ24',
    appId: '1:965170259379:ios:c9da254bd08327d4d4d7c6',
    messagingSenderId: '965170259379',
    projectId: 'pblkb-bf750',
    storageBucket: 'pblkb-bf750.firebasestorage.app',
    iosBundleId: 'com.example.pbl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmI1jXf0yve6zGY5Stc-BwI_HC9cmb6ZQ',
    appId: '1:965170259379:web:d008bd6e7d86fb6fd4d7c6',
    messagingSenderId: '965170259379',
    projectId: 'pblkb-bf750',
    authDomain: 'pblkb-bf750.firebaseapp.com',
    storageBucket: 'pblkb-bf750.firebasestorage.app',
  );
}
